_default:
  @just --list --unsorted

docker-build:
  docker build -t ansible-testing .

docker-run:
  docker run -it -v $(pwd):/ansible ansible-testing

test-playbook playbook:
  docker run -it -v $(pwd):/ansible ansible-testing ansible-playbook {{ playbook }} --limit 'local'

prod-playbook playbook:
  docker run -it -v $(pwd):/ansible ansible-testing ansible-playbook {{ playbook }} --limit 'prod'
